extends: eslint:recommended
env:
  es6: true
  node: true
  browser: false
rules:
  no-console:
    - warn
  no-multiple-empty-lines:
   - error
   - max: 1
     maxEOF: 1
  quotes:
    - error
    - single
